#!/usr/bin/env node
/**
 * Created by ggisbert on 7/10/15.
 * on heroku we cant hardcode to specific PORT, dynamic PORT,
 * Readoff and enviroment variable on Heroku
 * so we check if we have that env or we assign it the default 3000
 */

var app = require('./app');
var port = process.env.PORT || 3000;
app.listen(port, function(){
    console.log('Listening on port ' + port);
});